# Generated by Django 5.2 on 2025-04-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerprofile',
            name='company_proof',
            field=models.FileField(blank=True, help_text='Upload a PDF/PNG/JPG of your company proof.', null=True, upload_to='company_proofs/'),
        ),
    ]
