# Generated by Django 5.2 on 2025-05-05 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0004_job_requirements'),
        ('jobseekers', '0005_jobseekerprofile_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('hired', 'Hired')], default='applied', max_length=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
                ('job_seeker', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobseekers.jobseekerprofile')),
            ],
            options={
                'unique_together': {('job', 'job_seeker')},
            },
        ),
    ]
