# Generated by Django 5.2 on 2025-05-05 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('jobseekers', '0005_jobseekerprofile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_seeker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobseekers.jobseekerprofile'),
        ),
    ]
