# Generated by Django 5.1.7 on 2025-05-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_jobapplication_job_seeker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('hired', 'Hired'), ('withdrawn', 'Withdrawn')], default='applied', max_length=10),
        ),
    ]
