# Generated by Django 5.1.7 on 2025-05-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_jobapplication_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20),
        ),
    ]
