# Generated by Django 5.1.7 on 2025-04-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
