# Generated by Django 5.2 on 2025-04-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full-Time'), ('part_time', 'Part-Time'), ('remote', 'Remote'), ('internship', 'Internship'), ('freelance', 'Freelance')], default='full_time', max_length=20),
        ),
    ]
