# Generated by Django 5.2 on 2025-05-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(default='IT/CS', help_text='Enter job category (e.g., IT, Marketing, Sales)', max_length=100),
        ),
    ]
