# Generated by Django 5.2 on 2025-04-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0003_skill_remove_jobseekerprofile_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
    ]
